### ISSUE TITLE
One moment please

### ISSUE THREAD

**Issue by 89z** [Jarijaas/go-googleplay#2]
After I complete the Web login, the browser says "One moment please", but doesnt move past that.

**Comment by Jarijaas** [comment]
Did you try with different device configuration? Have you logged into that
account on this computer before using browser? Usually web login is not
required
pe 27. elok. 2021 klo 21.22 Steven Penny ***@***.***>
kirjoitti:

**Comment by 89z** [comment]
the message is getting sent to my actual phone, instead of the emulator I am using for testing
